services:
  kutt:
    image: kutt
    build: .
    depends_on:
      - postgres
      - redis
      - mailhog
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis
      REDIS_DB: "0"
      MAIL_PORT: "1025"
      MAIL_HOST: mailhog
      MAIL_SECURE: "false"
    networks:
    - kutt

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
    - kutt

  postgres:
    image: bitnami/postgresql:16.4.0-debian-12-r9
    environment:
      # 2 users will be available:
      # 1. postgres / pass
      # 2. user / pass
      POSTGRESQL_POSTGRES_PASSWORD: pass
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_DATABASE: kutt
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - kutt

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
    networks:
    - kutt

  casdoor:
    image: casbin/casdoor:v1.702.0
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./local/casdoor:/conf:ro
    networks:
      kutt:
        aliases:
          - casdoor-7f000001.nip.io
volumes:
  redis_data:
  postgres_data:

networks:
  kutt:
